#!/bin/bash
#
function error() {
  echo -e "\e[0;33mERROR: The Zero Touch Provisioning script failed while running the command $BASH_COMMAND at line $BASH_LINENO.\e[0m" >&2
}
trap error ERR

#SSH_URL="http://192.168.200.1/authorized_keys"
#Setup SSH key authentication for Ansible
#mkdir -p /home/cumulus/.ssh
#wget -O /home/cumulus/.ssh/authorized_keys $SSH_URL

# unexpire cumulus user password (new for 4.2)
passwd -x 99999 cumulus
#echo 'cumulus:CumulusLinux!' | chpasswd

#chmod 755 /etc/netq/netq.yml

#apt update -qy
#apt install -qy netq-apps netq-agent

# make user cumulus passowrdless sudo
echo "cumulus ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/10_cumulus

# allow ntp to make large steps at service restart
#echo "tinker panic 0" >> /etc/ntp.conf
#systemctl enable ntp@mgmt

#netq config restart cli
#netq config restart agent

#sed -i 's/LOG_LEVEL = INFO/LOG_LEVEL = DEBUG/' /etc/cumulus-air/agent.ini

# Pre-login banner
#cat <<EOT > /etc/issue
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#   Welcome to \n
#   Login with: cumulus/CumulusLinux!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#EOT
#cp /etc/issue /etc/issue.net
#chmod 755 /etc/issue /etc/issue.net

#reboot
#exit 0
#CUMULUS-AUTOPROVISIONING
